---
apiVersion: v1
kind: Namespace
metadata:
  name:  demo-pod-log-3

---
apiVersion: v1
kind: Pod
metadata:
  namespace: demo-pod-log-3
  name: demo-pod-log-3
spec:
  containers:
  - name: count1
    image: busybox
    args: [/bin/sh, -c,
            'i=0; while true; do echo "$i: $(date) - pod1"; i=$((i+1)); sleep 1; done']
  - name: count2
    image: busybox
    args: [/bin/sh, -c,
            'for i in $(seq 1 10); do echo "$i: $(date) - $(hostname)"; sleep 1;done']
