kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-rwx
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-vm-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-rwo
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-vm-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-rox
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-vm-storage"
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
