apiVersion: v1
kind: Pod
metadata:
  name: demo-pv-pod
spec:
  containers:
  - image: neotkm/pod-healthcheck:v0.03
    name: demo-pv-pod
    volumeMounts:
    - mountPath: /test-pv
      name: demo-pv
    - mountPath: /test-pv-2
      name: demo-pv-2
    - mountPath: /test-pv-3
      name: demo-pv-3
  - image: busybox
    name: demo-pv-pod-2
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /test-pv
      name: demo-pv
    - mountPath: /test-pv-2
      name: demo-pv-2
    - mountPath: /test-pv-3
      name: demo-pv-3
  volumes:
    - name: demo-pv
      persistentVolumeClaim:
        claimName: demo-pvc
    - name: demo-pv-2
      persistentVolumeClaim:
        claimName: demo-pvc2
    - name: demo-pv-3
      persistentVolumeClaim:
        claimName: demo-pvc3
