---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pv-rwo
spec:
  containers:
  - image: neotkm/pod-healthcheck:v0.03
    name: demo-pv-rwo
    volumeMounts:
    - mountPath: /test-pv-rwo
      name: demo-pv-rwo
  volumes:
    - name: demo-pv-rwo
      persistentVolumeClaim:
        claimName: claim-rwo

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pv-rwo-2
spec:
  containers:
  - image: neotkm/pod-healthcheck:v0.03
    name: demo-pv-rwo-2
    volumeMounts:
    - mountPath: /test-pv-rwo
      name: demo-pv-rwo
  volumes:
    - name: demo-pv-rwo
      persistentVolumeClaim:
        claimName: claim-rwo


---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pv-rwx
spec:
  containers:
  - image: neotkm/pod-healthcheck:v0.03
    name: demo-pv-rwx
    volumeMounts:
    - mountPath: /test-pv-rwx
      name: demo-pv-rwx
  volumes:
    - name: demo-pv-rwx
      persistentVolumeClaim:
        claimName: claim-rwx

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pv-rwx-2
spec:
  containers:
  - image: neotkm/pod-healthcheck:v0.03
    name: demo-pv-rwx-2
    volumeMounts:
    - mountPath: /test-pv-rwx
      name: demo-pv-rwx
  volumes:
    - name: demo-pv-rwx
      persistentVolumeClaim:
        claimName: claim-rwx

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pv-rox
spec:
  containers:
  - image: neotkm/pod-healthcheck:v0.03
    name: demo-pv-rox
    volumeMounts:
    - mountPath: /test-pv-rox
      name: demo-pv-rox
  volumes:
    - name: demo-pv-rox
      persistentVolumeClaim:
        claimName: claim-rox

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pv-rox-2
spec:
  containers:
  - image: neotkm/pod-healthcheck:v0.03
    name: demo-pv-rox-2
    volumeMounts:
    - mountPath: /test-pv-rox
      name: demo-pv-rox
  volumes:
    - name: demo-pv-rox
      persistentVolumeClaim:
        claimName: claim-rox
