---
apiVersion: v1
kind: Namespace
metadata:
  name: statefulset-demo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-demo
  labels:
    app: statefulset-demo
  namespace: statefulset-demo
spec:
  serviceName: statefulset-demo
  replicas: 5
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 3
  selector:
    matchLabels:
      app: statefulset-demo
  template:
    metadata:
      labels:
        app: statefulset-demo
    spec:
      containers:
      - name: statefulset-demo
        image: neotkm/pod-healthcheck:v0.03
