---
apiVersion: v1
kind: Namespace
metadata:
  name:  demo-secret-pod


---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: demo-secret-pod
type: Opaque
data:
  password: 4oCYSGdHU2NleXJlIzI04oCZ
  username: ZGV2dXNlcg==
