apiVersion: v1
kind: Pod
metadata:
  name: demo-emptydir-volume-ram
spec:
  containers:
  - name: demo-emptydir-volume-ram
    image: neotkm/pod-healthcheck:v0.03
    volumeMounts:
    - name: emptydir-demo-ram
      mountPath: /data/emptydir-ram
  - name: demo-emptydir-volume-2
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: emptydir-demo-ram
      mountPath: /data/emptydir-ram2
  volumes:
  - name: emptydir-demo-ram
    emptyDir:
      medium: Memory
