apiVersion: v1
kind: Pod
metadata:
  name: demo-emptydir-volume
spec:
  containers:
  - name: demo-emptydir-volume
    image: neotkm/pod-healthcheck:v0.03
    volumeMounts:
    - name: emptydir-demo
      mountPath: /data/emptydir
  - name: demo-emptydir-volume-2
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: emptydir-demo
      mountPath: /data/emptydir
  volumes:
  - name: emptydir-demo
    emptyDir: {}
