apiVersion: v1
kind: Pod
metadata:
  name: demo-local-volume-pod
spec:
  containers:
  - image: neotkm/pod-healthcheck:v0.03
    name: demo-local-volume-pod
    volumeMounts:
    - mountPath: /test-pv
      name: local-pv
  - image: busybox
    name: demo-local-volume-pod-2
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /test-pv
      name: local-pv
  volumes:
    - name: local-pv
      persistentVolumeClaim:
        claimName: local-pvc
